### ISSUE TITLE
Video in repository will slow down downloads

### ISSUE THREAD

**Issue by rubenwardy** [Extex101/motorbike#1]
Create a file called `.gitattributes` with the following content:

```
*.mp4		export-ignore
```

This will prevent the video appearing in the ContentDB download

**Comment by Extex101** [comment]
Ok tnx will do that
I did it like this:
``Bike_video_HD720p.mp4		export-ignore``
Is that right?

**Comment by rubenwardy** [comment]
If you post the exact content I gave, it'll work with any MP4 file, but it doesn't actually matter that much. For your line:

* You need to separate it with a tab 
* Make sure the exact same capitalisation is used

After you do this, you can test it by making a contentdb release

**Comment by rubenwardy** [comment]
Oh I see you have used a tab in the actual version. Therefore it should work. Create a release on content dB then download it from the website and check its contents

**Comment by Extex101** [comment]
Ok it works. Mp4 isn't downloaded from CDB
