### ISSUE TITLE
Texture issue

### ISSUE THREAD

**Issue by BeverlyCode** [Extex101/motorbike#15]
![image](https://github.com/Extex101/motorbike/assets/118085961/9a9d65f4-8084-433e-8fea-a6e218b72336)

Might be related to the this issue https://github.com/minetest/minetest/issues/13423

**Comment by Extex101** [comment]
What version of Minetest are you using?

**Comment by BeverlyCode** [comment]
> What version of Minetest are you using?

5.4.1 from Ubuntu repo, the textures seem to work on 5.7.0 but the back wheel looks darker at night.

![image](https://github.com/Extex101/motorbike/assets/118085961/430e7767-7aae-4521-b0cb-0b5fa31ad710)

Look OK in the day though:

![image](https://github.com/Extex101/motorbike/assets/118085961/1a4124d1-c5e8-4a0b-b73b-97f86852c069)

**Comment by Extex101** [comment]
Fixed #16

**Comment by BeverlyCode** [comment]
Amazing, the textures are also working great now on 5.4.1
