### ISSUE TITLE
attached driver leaves -> crashes server

### ISSUE THREAD

**Issue by timelincoln7648** [Extex101/motorbike#3]
<img width="963" alt="Screen Shot 2020-09-15 at 2 25 21 PM" src="https://user-images.githubusercontent.com/5668620/93257898-2dc61280-f763-11ea-95be-218ec904bc1c.png">

Hi there I love this mod thanks so much! I'm having an issue where my server crashes when a player leaves while still on a bike, I checked the force_detach(player) function and tried forcing entity.driver = nil, but now I'm wondering if the function is correctly able to grab the entity after the player is already gone? 

I'm using a checkout of the mod at [this commit](https://github.com/Extex101/motorbike/commit/e233b3dc7e019bfc492aa0dff84a88e3ddf30420) (because i didn't want the sounds for what I'm doing, even tho I think they're great :))

**Comment by Extex101** [comment]
I don't see what the problem could be 🤔 
Perhaps try using the most recent one but just delete the play sound code

**Comment by Extex101** [comment]
Ok I pretty sure it's fixed now
