### ISSUE TITLE
Crash when right click a motorbike

### ISSUE THREAD

**Issue by Backlund** [Extex101/motorbike#9]
Fedora 35
MineTest 5.5.0

2022-04-04 23:56:40: ACTION[Server]: singleplayer right-clicks object 2: LuaEntitySAO "motorbike:bike_green" at (211,11,-281)
2022-04-04 23:56:40: ERROR[Main]: ServerError: AsyncErr: Lua: Runtime error from mod 'motorbike' in callback luaentity_run_simple_callback(): <.minetest/mods/motorbike/functions.lua:206: attempt to index a nil value
2022-04-04 23:56:40: ERROR[Main]: stack traceback:
2022-04-04 23:56:40: ERROR[Main]: 	<.minetest/mods/motorbike/functions.lua:206: in function 'attach'
2022-04-04 23:56:40: ERROR[Main]: 	<.minetest/mods/motorbike/init.lua:91: in function <.minetest/mods/motorbike/init.lua:89>
2022-04-04 23:56:40: ACTION[Server]: singleplayer leaves game. List of players: 

It works on Android and Ubuntu, but not on my Fedora computer.

**Comment by Extex101** [comment]
Have you got player_api installed in your game? Only newer Minetest Game versions that have player_api will work

**Comment by Backlund** [comment]
I installed all dependencies.

I commented out line 206 in functions.lua just for test, then I could ride the motorbike, but the player model became a green pixel model without animations when I got off.

**Comment by Extex101** [comment]
Ok.. What did you look like before you got on? Just regular player model?

**Comment by Backlund** [comment]
Yes, just regular player model.

**Comment by Extex101** [comment]
Ok well it's saying that player_api is a nil value.
If you've got player_api installed as you say, I can't imagine what the problem could be.

**Comment by Backlund** [comment]
I think I fixed it.
I noticed you already put the player properties in a local variable in that function. local props = player:get_properties()
so i changed entity.info.model = player_api.get_animation(player).model to
entity.info.model = props.mesh

No need to call the api to get the model again when you already had it in a local variable.

**Comment by dragonfly-ai** [comment]
I just commented out that line and that seemed to fix it.  Much cooler mod when it doesn't crash the game. :)

**Comment by Extex101** [comment]
Ah, it seems there have been some changes to player_api that I was not aware of.
I'll take a look on Monday.

**Comment by Backlund** [comment]
> I just commented out that line and that seemed to fix it.  Much cooler mod when it doesn't crash the game. :)

What does your player model look like when you get off the bike?

**Comment by dragonfly-ai** [comment]
When it gets on the bike it assumes the correct pose, but armor disappears.  When it gets off, the armor reappears. 
Yesterday after multiple rides, I switched to chase camera mode and saw the player model standing upright in the center of the bike, fully armored, but I haven't been able to reproduce today.

My kid is very excited to try your mod.  Do you have plans to add a motocross track to world generator?

**Comment by Extex101** [comment]
Oops my finger slipped
> My kid is very excited to try your mod. Do you have plans to add a motocross track to world generator?

I'd recommended [The Low Road](https://forum.minetest.net/viewtopic.php?t=18529). It's what I used when I was testing. You'd need to use it on a fresh world though.

**Comment by Extex101** [comment]
Ok this whole mod is a mess, I have a load of refactoring to do. I just want you to know that I _am_ working on it, though it may take some time.

**Comment by dragonfly-ai** [comment]
"I have a load of refactoring to do" not easy in Lua, so far as I know.  Do you have to restart the game between every change?  I haven't noticed any tooling for minetest mods.  Is there anything that the community could do to help?

Thanks for building and maintaining the mod, though.  My son and I dug out a neat underground race track with jumps and obstacles. We're having a lot of fun even with the semi-functional version.

**Comment by Extex101** [comment]
I apologize I've been having some trouble recently and haven't been able to work on this.

**Comment by dragonfly-ai** [comment]
For what we're paying you, we can't complain.  Well wishes for you, though, through any hard times.

If you could suggest a direction or general approach to the problem, I could try to pitch in with a pull request.  LMK.  :)

**Comment by depascalis** [comment]
How's it going with this issue? The kids are driving me nuts about this mod 😂

**Comment by Extex101** [comment]
I did some more work on it recently, the code is rather only and messy so I started a rewrite. I haven't had much time recently so I haven't been able to do much.

All that's left to is reimplement the crafting recipes, the colours of bikes, reimplement skidding and fix braking. As well as some minor refactoring

**Comment by Extex101** [comment]
Ok I've got it working, just need to re-implement the sound effect code and clean up a tiny bit then it's ready for release.
Should be ready sometime later today

**Comment by Extex101** [comment]
Finally done. #11 Merged, let me know if you've got any further issues. Sorry for the delay.
